### ISSUE TITLE
Form Parameters for generating invoice

### ISSUE THREAD

**Issue by Prithviraj2003** [keizerworks/invoicen#11]
### Description

**Invoice Details :** 

1. Invoice Number): Input field (text)
2. Bill Date: Input field (date)
3. Delivery Date: Input field (date)
4. Terms of Payment: Input field (text, e.g., "Within 15 days")
5. Payment Deadline: Input field (date)

**Seller Details (Your Company Information) :**

1. Company Name: Input field (text)
2. Address: Input field (textarea)
3. Phone Number: Input field (text)
4. Email: Input field (email)
5. SIRET: Input field (text)
6. GSTIN: Input field (text)

**Billing Address :**

1. Customer Name: Input field (text)
2. Address: Input field (textarea)
3. Phone Number: Input field (text)
4. Email: Input field (email)
5. SIRET: Input field (text)
6. GSTIN: Input field (text)

**Items (Dynamic List) :**

1. Article: Input field (text)
2. Quantity: Input field (number)
3. Unit Price: Input field (number)
4. TAX: Input field (percentage, number)
Button to "Add Item" (to handle multiple items)

Are these form fields sufficient ??

### Are you willing to submit PR?

Yes

**Comment by aayushchugh** [comment]
Hey @Prithviraj2003 thanks for your interest in this project, I am working on this issue. If we need your help, we'll create issues with help-wanted label
