### ISSUE TITLE
feat: improve UI

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/invoicen#13]
#12 will only focus on features instead of UI so we need to create a better UI after #12 is closed

**Comment by pavanydg** [comment]
@aayushchugh is there any figma design?

**Comment by aayushchugh** [comment]
We are working on it, I'll add a link to figma file in readme once finalised

**Comment by pavanydg** [comment]
would like to work on it.

**Comment by aayushchugh** [comment]
Completed in #30
