### ISSUE TITLE
[FEAT] :sparkles: skeleton for nav loading

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/invoicen#16]
### Description

Our navbar takes time to load because of Next Image and dynamic theme configuration. We need to create a skeleton loading indicator.

### Anything else?

https://ui.shadcn.com/docs/components/skeleton

### Are you willing to submit PR?

No

**Comment by tushar-daiya** [comment]
It loads for me instantly.. even if you want a skeleton I am willing to submit a PR

**Comment by Prithviraj2003** [comment]
![Screenshot 2024-11-04 155112](https://github.com/user-attachments/assets/3d2de272-dd76-435c-8edb-02a10a3e933f)

![image](https://github.com/user-attachments/assets/4c67a487-6b29-4090-ad35-ccbd90c8d30c)


I am using bg-gray-300 for the skeleton any better colour for it ?

**Comment by aayushchugh** [comment]
@Prithviraj2003 are you using skeleton from shadcn/ui or did you build your custom one?

**Comment by Prithviraj2003** [comment]
I am using Shadcn/ui

**Comment by aayushchugh** [comment]
@Prithviraj2003  use `bg-muted` as colour, everything else looks great. Thanks for your efforts

**Comment by Prithviraj2003** [comment]
> @Prithviraj2003 use `bg-muted` as colour, everything else looks great. Thanks for your efforts.
> 
> `bg-muted` syncs with dark and light theme

Sure
