### ISSUE TITLE
[FEAT] :sparkles: discount field in entries

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/invoicen#21]
### Description

We need to add an option for discounts in entries.

This field is optional

### Anything else?

user feedback:

![image](https://github.com/user-attachments/assets/82b7c891-ed89-48cf-bc1d-d9ed066bd0b6)

### Are you willing to submit PR?

No

**Comment by Prithviraj2003** [comment]
@aayushchugh Discount will be percentage like 10% which will be applied to all the entries or direct discount of $100 or $50/entry ??

**Comment by aayushchugh** [comment]
@Prithviraj2003 Yes discount will be in percentage but @DMZTdhruv is already working on this one

**Comment by yashkolambekar** [comment]
> [@Prithviraj2003](https://github.com/Prithviraj2003) Yes discount will be in percentage but [@DMZTdhruv](https://github.com/DMZTdhruv) is already working on this one

should be an option to add both, atleast on the ui level, datbase can hold just the values, giving both (percentage and amount/numvbers) options is better for ux

**Comment by aayushchugh** [comment]
@yashkolambekar That's a good point

**Comment by mohdshubair313** [comment]
Hey @aayushchugh Can I work on this issue??

**Comment by aayushchugh** [comment]
@mohdshubair313 Sure! You'r help will be appreciated. Please let us know your plan and how you'll manage the discount fields

**Comment by mohdshubair313** [comment]
simply change database and add discount and update api to handle discount field and changes UI to reflect the discount field

**Comment by aayushchugh** [comment]
@mohdshubair313 There are no APIs as of now. This is a static app

**Comment by mohdshubair313** [comment]
yeah I see this is static and I want to ask some question is 
where I have to put this discount filed like in UI and invoice where is this be shown?

**Comment by aayushchugh** [comment]
You can add a new field in Invoice before `total` where we can add discount on total bill

**Comment by mohdshubair313** [comment]
![image](https://github.com/user-attachments/assets/695ff687-5b77-477e-8c3c-6155fe7d89ed)
Hey can you review it , is it correct discount showing invoice in pdf

**Comment by pavanydg** [comment]
@aayushchugh is this still open?

**Comment by aayushchugh** [comment]
@pavanydg Yeah this is open but we'll work on this after sometime.

I'll close this for now
