### ISSUE TITLE
[BUG] :bug: fix total amount to 2 decimal places

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/invoicen#35]
### Current Behaviour

<img width="410" alt="image" src="https://github.com/user-attachments/assets/f070f8ba-bcf2-4c9a-a7dd-977eb072095a">

### Expected Behaviour

Total amount should be fixed to 2 decimal places

### Steps To Reproduce

1. Go to generate invoice page
2. Keep increasing tax until you see multiple decimal places

### Are you willing to submit PR?

No

**Comment by arashveysi3** [comment]
working on it

**Comment by arashveysi3** [comment]
Dude @Mihir2423 how about leaving a damn comment on the issue before start to creating a PR

**Comment by Mihir2423** [comment]
> Dude @Mihir2423 how about leaving a damn comment on the issue before start to creating a PR

i didn't even see your "Damned comment" before raising the PR o,o

**Comment by aayushchugh** [comment]
Guys, please make sure you are assigned to the issue before raising the PR
