### ISSUE TITLE
chore: create issue templates for GitHub issues

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/invoicen#4]
Reference: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by pavanydg** [comment]
@aayushchugh i would like to work on this.

**Comment by rovertrack** [comment]
So you need a custom issue template for this repository 
So that It  looks good for contributors

**Comment by aayushchugh** [comment]
Yup, that's what we want to do.

**Comment by kom-senapati** [comment]
Give me some details, I would like to add if you want!

**Comment by aayushchugh** [comment]
@kom-senapati I have already created these, forgot to close the issue
