### ISSUE TITLE
use eslint+prettier instead of biome

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/invoicen#41]
The majority of people don't use biome as their default format and lining tool so it is ideal to use eslint+prettier instead of biome

**Comment by Sudarsh1010** [comment]
I will add this

**Comment by Sudarsh1010** [comment]
https://gist.github.com/Sudarsh1010/3aa39b7a46811acbbddee8fbea14d1fb
@aayushchugh take a look at this

**Comment by aayushchugh** [comment]
@Sudarsh1010 Can you please add 2 more rules for 

1. console.log
2. Unused vars

**Comment by Sudarsh1010** [comment]
ok, and this lint config will also enforce you to use kebab case

**Comment by aayushchugh** [comment]
Completed in #52
