### ISSUE TITLE
[BUG] :bug: Inconsistent Currency in PDF Invoice

### ISSUE THREAD

**Issue by geekyharsh05** [keizerworks/invoicen#48]
### Current Behaviour

When the currency is selected as INR, the product prices in the generated PDF invoice are still displayed in USD. This creates inconsistency between the selected currency and the displayed values.

### Expected Behaviour

When the currency is selected as INR, the product prices should be displayed in INR.

### Steps To Reproduce

1. Go to the invoice generation page in the application.  
2. Select **INR** as the currency for the invoice.  
3. Add products with their prices.  
4. Generate and download the PDF invoice.  
5. Observe that the product prices in the invoice are displayed in USD instead of INR.  

### Invoice Generation Page
<img width="1440" alt="Screenshot 2024-12-08 at 2 55 39 AM" src="https://github.com/user-attachments/assets/42addfe3-2d63-4d0a-b78f-faf2129b399f"> <br/>

#### Here the product entries price is in USD but it should be displayed in INR.
<img width="665" alt="Screenshot 2024-12-08 at 2 56 01 AM" src="https://github.com/user-attachments/assets/688c23c0-627a-434b-8290-f17347e8ea21">

### Are you willing to submit PR?

Yes

**Comment by PratapRathi** [comment]
Please assign to me, I am working on it.
