### ISSUE TITLE
[FEAT] :sparkles: Create docker file and docker compose

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/invoicen#53]
### Description

We need a docker file and docker compose for production and local development.

## Services required in docker compose

1. Postgres
2. MinIO
3. Redis
4. mailhog

### Anything else?

Docker compose is available here: https://github.com/keizerworks/keizer-init/blob/main/docker-compose.yml

### Are you willing to submit PR?

No

**Comment by pavanydg** [comment]
@aayushchugh i am willing to work on this. Pls assign this to me.

**Comment by aayushchugh** [comment]
Sure @pavanydg
