### ISSUE TITLE
[FEAT] :sparkles: setup git husky to lint and format code before committing

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/invoicen#56]
### Description

https://typicode.github.io/husky/

### Are you willing to submit PR?

No

**Comment by userAdityaa** [comment]
Hey @aayushchugh, assign this to me.

**Comment by aayushchugh** [comment]
Sure @userAdityaa

**Comment by Sudarsh1010** [comment]
@aayushchugh why is this re-opened?
