### ISSUE TITLE
[FEAT] :sparkles: option to remove tax section

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/invoicen#70]
### Description

We need an option to remove tax section or simply don't render tax section in pdf if there are no tax details added.

### Anything else?

Make sure to do these changes in `main` branch instead of `v2`

### Are you willing to submit PR?

No

<sub><a href="https://huly.app/guest/keizerworks?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZjNTYwZGYxNDRmNTg1YWU1MDUyMmUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2VpemVyd29ya3Mta2VpemVyd29ya3MtNjc2YmIzYzQtNTg1NDc1Mzg4My00NDc3M2YifQ.vZ43_kTHz1P6_ocr2TSoNk7llljO00659UHPyaXHsTM">Huly&reg;: <b>INVOI-70</b></a></sub>

**Comment by SanskarSawant23** [comment]
can you assign me this issue?

**Comment by aayushchugh** [comment]
Sure @SanskarSawant23

**Comment by dhanushd-27** [comment]
Can others help with this issue, or is it just for the person assigned to it?
