### ISSUE TITLE
[FEAT] :sparkles: Reset/Forgot Password

### ISSUE THREAD

**Issue by Sudarsh1010** [keizerworks/invoicen#76]
### Description

We should have option to reset password, if user forgot password, they request.

refer this: <https://github.com/lucia-auth/example-nextjs-email-password-2fa/blob/main/app/forgot-password/page.tsx>

### Are you willing to submit PR?

No

<sub><a href="https://huly.app/guest/keizerworks?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZlZDRlMWYxNDRmNTg1YWU1MTIwNmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2VpemVyd29ya3Mta2VpemVyd29ya3MtNjc2YmIzYzQtNTg1NDc1Mzg4My00NDc3M2YifQ.A3_eEcp2C4QRMwILW-IOIyK1Zvdn99WW3cCGjmaOWPE">Huly&reg;: <b>INVOI-76</b></a></sub>

**Comment by Prithviraj2003** [comment]
@Sudarsh1010 can you assign this to me ?

**Comment by Sudarsh1010** [comment]
sure
