### ISSUE TITLE
[BUG] :bug: Peer dependency conflict while project setup

### ISSUE THREAD

**Issue by Yh010** [keizerworks/invoicen#9]
### Current Behaviour

while setting up the project, I face this issue:

D:\Projects\OpenSource\invoicen>npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: invoicen@0.1.0
npm error Found: react@19.0.0-rc-02c0e824-20241028
npm error node_modules/react
npm error   react@"19.0.0-rc-02c0e824-20241028" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.x || ^17.x || ^18.x || ^19.x" from @radix-ui/react-icons@1.3.1
npm error node_modules/@radix-ui/react-icons
npm error   @radix-ui/react-icons@"^1.3.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\Yash U Hegde\AppData\Local\npm-cache\_logs\2024-11-02T07_34_34_241Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\Yash U Hegde\AppData\Local\npm-cache\_logs\2024-11-02T07_34_34_241Z-debug-0.log

### Expected Behaviour

Maybe use a stable version of react or should we proceed with :
npm install --legacy-peer-deps
 
?

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you willing to submit PR?

Yes

**Comment by aayushchugh** [comment]
You need to run `npm i` with `--force` flag. This is because of nextjs 15 and shadcn

https://ui.shadcn.com/docs/react-19
